name: Automation Test and Merge PR

on:
  workflow_dispatch:
    inputs:
      result:
        description: 'Test result (success or failure)'
        required: true
        type: string
      sha:
        description: 'Commit SHA to set status'
        required: true
        type: string
      pr_number:
        description: 'Pull request number to merge'
        required: true
        type: string

jobs:
  automation-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Set PR status to pending
      - name: Set PR status to pending
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -d '{
              "state": "pending", 
              "context": "Automation Test",
              "description": "Tests are running. Please wait."
            }'

      # Step 2: Process test result
      - name: Process result from Spring Boot
        run: |
          if [ "${{ github.event.inputs.result }}" == "success" ]; then
            echo "Tests passed!"
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.inputs.sha }} \
              -d '{
                "state": "success", 
                "context": "Automation Test",
                "description": "Tests passed!"
              }'
          else
            echo "Tests failed!"
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.inputs.sha }} \
              -d '{
                "state": "failure", 
                "context": "Automation Test",
                "description": "Tests failed!"
              }'
          fi

      # Step 3: Decision to merge PR
      - name: Decide whether to merge PR based on test result
        if: ${{ github.event.inputs.result == 'success' }}
        run: |
          echo "Tests passed. Merging PR..."
          curl -X PUT \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.inputs.pr_number }}/merge \
            -d '{
              "commit_title": "Merging PR after successful automation test",
              "merge_method": "squash"
            }'
          
      # Step 4: If test failed, don't merge
      - name: Don't merge PR if tests failed
        if: ${{ github.event.inputs.result == 'failure' }}
        run: |
          echo "Tests failed. PR will not be merged."
