name: Automation Test for PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  automation-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      # Step 3: Set PR status to pending
      - name: Set PR status to pending
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -d '{
              "state": "pending", 
              "context": "Automation Test",
              "description": "Tests are running. Please wait."
            }'

      # Step 4: Send request to Spring Boot application for testing
      - name: Send request to Spring Boot application
        run: |
          curl -X POST "https://8deb-2405-201-4041-182c-18a5-3013-2d6a-5d0d.ngrok-free.app/github-webhook" \
            -H "Content-Type: application/json" \
            -d '{
              "owner": "${{ github.repository_owner }}",
              "repo": "${{ github.event.repository.name }}",
              "sha": "${{ github.sha }}",
              "pr_number": "${{ github.event.pull_request.number }}",
              "callback_url": "https://api.github.com/repos/${{ github.repository }}/actions/workflows/automation-test-and-merge-pr.yml/dispatches"
            }'

  handle-callback:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      # Step 5: Set PR status based on result from Spring Boot
      - name: Set PR status based on result
        run: |
          if [ "${{ github.event.inputs.result }}" == "success" ]; then
            STATUS="success"
            DESCRIPTION="Tests passed."
          else
            STATUS="failure"
            DESCRIPTION="Tests failed."
          fi
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.inputs.sha }} \
            -d "{
              \"state\": \"$STATUS\", 
              \"context\": \"Automation Test\",
              \"description\": \"$DESCRIPTION\"
            }"
